#!/usr/bin/env bash
set -e

for POSTGRESQL_SCHEMA in $(echo ${POSTGRESQL_SCHEMAS:-public} | tr ";" "\n")
do
  # verify user permission and extensions are on the database
  psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
  GRANT ALL PRIVILEGES ON DATABASE ${POSTGRESQL_DATABASE} TO ${POSTGRESQL_USER};
  \c ${POSTGRESQL_DATABASE};
  CREATE SCHEMA IF NOT EXISTS "${POSTGRESQL_SCHEMA}";
  GRANT ALL PRIVILEGES ON SCHEMA "${POSTGRESQL_SCHEMA}" TO ${POSTGRESQL_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA "${POSTGRESQL_SCHEMA}" GRANT ALL PRIVILEGES ON TABLES TO ${POSTGRESQL_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA "${POSTGRESQL_SCHEMA}" GRANT ALL PRIVILEGES ON SEQUENCES TO ${POSTGRESQL_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA "${POSTGRESQL_SCHEMA}" GRANT ALL PRIVILEGES ON FUNCTIONS TO ${POSTGRESQL_USER};
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  CREATE EXTENSION IF NOT EXISTS "tablefunc";
  CREATE EXTENSION IF NOT EXISTS "pgcrypto";
  CREATE EXTENSION IF NOT EXISTS "pg_trgm";
EOSQL
done
